// market/src/lib/mock-data/projects.ts
import { Project } from '../../types/project';

export const projects: Project[] = [
  {
    id: '1',
    title: 'Modern E-commerce Dashboard',
    description: 'Complete admin dashboard for e-commerce platforms with analytics, product management, order tracking, and customer insights. Built with modern React patterns and TypeScript for maximum maintainability.',
    shortDescription: 'Complete admin dashboard for e-commerce platforms with analytics and management tools.',
    sellerId: 'seller_1',
    sellerName: 'Sarah Johnson',
    sellerAvatar: '/images/avatars/sarah.jpg',
    
    techStack: ['React', 'TypeScript', 'Tailwind CSS', 'Chart.js', 'Framer Motion'],
    framework: 'Next.js 14',
    database: 'PostgreSQL',
    deployment: ['Vercel', 'Netlify', 'AWS'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    
    screenshots: ['/images/projects/dashboard-1.jpg', '/images/projects/dashboard-2.jpg'],
    demoUrl: 'https://ecommerce-dashboard-demo.vercel.app',
    videoUrl: 'https://youtube.com/watch?v=demo1',
    documentationUrl: '/docs/ecommerce-dashboard',
    
    price: 79.99,
    licenseType: 'commercial',
    
    category: 'dashboard',
    subcategory: 'ecommerce',
    tags: ['dashboard', 'admin', 'ecommerce', 'analytics', 'react'],
    
    downloads: 1245,
    views: 8932,
    rating: 4.8,
    reviewCount: 89,
    
    featured: true,
    trending: true,
    isNew: false,
    
    // Request-based purchase settings
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    
    // Request statistics
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-03-10T00:00:00Z'
  },
  {
    id: '2',
    title: 'React Native Food Delivery App',
    description: 'Complete food delivery mobile app with user authentication, restaurant listings, cart management, real-time order tracking, and payment integration. Includes both customer and restaurant owner interfaces.',
    shortDescription: 'Complete food delivery mobile app with real-time tracking and payment integration.',
    sellerId: 'seller_2',
    sellerName: 'Mike Chen',
    sellerAvatar: '/images/avatars/mike.jpg',
    
    techStack: ['React Native', 'TypeScript', 'Redux Toolkit', 'Stripe', 'Firebase'],
    framework: 'Expo SDK 49',
    database: 'Firebase Firestore',
    deployment: ['App Store', 'Google Play', 'Expo'],
    browserCompat: ['iOS Safari', 'Chrome Mobile'],
    mobileResponsive: true,
    
    screenshots: ['/images/projects/food-app-1.jpg', '/images/projects/food-app-2.jpg'],
    demoUrl: 'https://expo.dev/@demo/food-delivery',
    videoUrl: 'https://youtube.com/watch?v=demo2',
    
    price: 149.99,
    licenseType: 'extended',
    
    category: 'mobile-apps',
    subcategory: 'react-native',
    tags: ['mobile', 'food-delivery', 'react-native', 'payments', 'real-time'],
    
    downloads: 567,
    views: 4521,
    rating: 4.9,
    reviewCount: 43,
    
    featured: false,
    trending: true,
    isNew: true,
    
    // Request-based purchase settings
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    
    // Request statistics
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    
    createdAt: '2024-02-20T00:00:00Z',
    updatedAt: '2024-03-15T00:00:00Z'
  },
  {
    id: '3',
    title: 'Vue.js SaaS Landing Page',
    description: 'Modern, conversion-optimized landing page template for SaaS products. Features responsive design, smooth animations, pricing tables, testimonials, and contact forms. Fully customizable and SEO-friendly.',
    shortDescription: 'Modern, conversion-optimized landing page template for SaaS products.',
    sellerId: 'seller_3',
    sellerName: 'Emma Wilson',
    sellerAvatar: '/images/avatars/emma.jpg',
    
    techStack: ['Vue.js', 'Nuxt.js', 'Tailwind CSS', 'GSAP', 'TypeScript'],
    framework: 'Nuxt.js 3',
    database: 'None',
    deployment: ['Vercel', 'Netlify', 'Static Hosting'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    
    screenshots: ['/images/projects/saas-landing-1.jpg', '/images/projects/saas-landing-2.jpg'],
    demoUrl: 'https://vue-saas-landing.netlify.app',
    
    price: 39.99,
    licenseType: 'personal',
    
    category: 'landing-pages',
    tags: ['vue', 'saas', 'landing-page', 'responsive', 'animations'],
    
    downloads: 892,
    views: 3421,
    rating: 4.6,
    reviewCount: 67,
    
    featured: true,
    trending: false,
    isNew: false,
    
    // Request-based purchase settings
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    
    // Request statistics
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    
    createdAt: '2023-11-10T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z'
  },
  // Request-based projects
  {
    id: 'proj_1',
    title: 'E-commerce React Template',
    description: 'A modern e-commerce template built with React and TypeScript',
    shortDescription: 'Modern e-commerce template',
    sellerId: 'seller_1',
    sellerName: 'John Developer',
    sellerAvatar: '/avatars/john.jpg',
    techStack: ['React', 'TypeScript', 'Tailwind CSS'],
    framework: 'Next.js',
    database: 'PostgreSQL',
    deployment: ['Vercel', 'Netlify'],
    browserCompat: ['Chrome', 'Firefox', 'Safari'],
    mobileResponsive: true,
    screenshots: ['/screenshots/ecommerce-1.jpg', '/screenshots/ecommerce-2.jpg'],
    demoUrl: 'https://demo.example.com',
    price: 299,
    licenseType: 'commercial',
    category: 'Web Templates',
    subcategory: 'E-commerce',
    tags: ['react', 'ecommerce', 'typescript'],
    downloads: 150,
    views: 1200,
    rating: 4.8,
    reviewCount: 45,
    featured: true,
    trending: false,
    isNew: false,
    isRequestOnly: true,
    state: 'pending_request',
    requiresApproval: true,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 2,
    pendingRequests: 1,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 1,
    lastRequestAt: '2024-01-20T10:30:00Z',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z'
  },
  {
    id: 'proj_2',
    title: 'Mobile App UI Kit',
    description: 'Complete UI kit for mobile applications with 50+ components',
    shortDescription: 'Mobile UI kit with 50+ components',
    sellerId: 'seller_2',
    sellerName: 'Sarah Designer',
    sellerAvatar: '/avatars/sarah.jpg',
    techStack: ['React Native', 'Figma', 'Sketch'],
    framework: 'React Native',
    deployment: ['iOS', 'Android'],
    browserCompat: ['iOS Safari', 'Chrome Mobile'],
    mobileResponsive: true,
    screenshots: ['/screenshots/mobile-1.jpg', '/screenshots/mobile-2.jpg'],
    price: 199,
    licenseType: 'commercial',
    category: 'Mobile UI',
    subcategory: 'UI Kits',
    tags: ['mobile', 'ui', 'react-native'],
    downloads: 89,
    views: 650,
    rating: 4.6,
    reviewCount: 23,
    featured: false,
    trending: true,
    isNew: true,
    isRequestOnly: true,
    state: 'available_for_request',
    requiresApproval: true,
    autoApprove: false,
    maxRequestsPerBuyer: 2,
    totalRequests: 2,
    pendingRequests: 0,
    approvedRequests: 1,
    rejectedRequests: 1,
    completedRequests: 0,
    lastRequestAt: '2024-01-19T14:20:00Z',
    createdAt: '2024-01-20T14:30:00Z',
    updatedAt: '2024-01-20T14:30:00Z'
  }
  ,
  // Additional mock projects for testing infinite scroll
  {
    id: 'mock_1',
    title: 'Starter Portfolio Template',
    description: 'Clean and modern portfolio template built with Next.js and Tailwind CSS.',
    shortDescription: 'Clean Next.js portfolio',
    sellerId: 'seller_4',
    sellerName: 'Alex Green',
    sellerAvatar: '/images/avatars/alex.jpg',
    techStack: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    framework: 'Next.js 14',
    database: 'None',
    deployment: ['Vercel'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/portfolio-1.jpg'],
    demoUrl: 'https://portfolio-demo.example.com',
    price: 19.99,
    licenseType: 'personal',
    category: 'portfolio',
    tags: ['nextjs', 'portfolio', 'tailwind'],
    downloads: 120,
    views: 980,
    rating: 4.4,
    reviewCount: 12,
    featured: false,
    trending: false,
    isNew: true,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z'
  },
  {
    id: 'mock_2',
    title: 'SaaS Admin Kit',
    description: 'Production-ready admin components for SaaS dashboards with auth and charts.',
    shortDescription: 'Admin components for SaaS',
    sellerId: 'seller_5',
    sellerName: 'Priya Singh',
    sellerAvatar: '/images/avatars/priya.jpg',
    techStack: ['React', 'TypeScript', 'Tailwind CSS', 'Chart.js'],
    framework: 'Vite',
    database: 'None',
    deployment: ['Netlify', 'Vercel'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/saas-admin-1.jpg'],
    price: 59.00,
    licenseType: 'commercial',
    category: 'dashboard',
    tags: ['dashboard', 'saas', 'react'],
    downloads: 320,
    views: 2100,
    rating: 4.7,
    reviewCount: 34,
    featured: true,
    trending: true,
    isNew: false,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2024-01-22T00:00:00Z',
    updatedAt: '2024-02-10T00:00:00Z'
  },
  {
    id: 'mock_3',
    title: 'Mobile E-commerce UI',
    description: 'Beautiful mobile e-commerce UI kit with cart and checkout flows.',
    shortDescription: 'Mobile e-commerce UI kit',
    sellerId: 'seller_6',
    sellerName: 'Diego Alvarez',
    sellerAvatar: '/images/avatars/diego.jpg',
    techStack: ['React Native', 'Expo'],
    framework: 'Expo SDK 49',
    database: 'None',
    deployment: ['iOS', 'Android'],
    browserCompat: ['iOS Safari', 'Chrome Mobile'],
    mobileResponsive: true,
    screenshots: ['/images/projects/mobile-ecom-1.jpg'],
    price: 89.00,
    licenseType: 'commercial',
    category: 'mobile-apps',
    tags: ['mobile', 'ui-kit'],
    downloads: 85,
    views: 740,
    rating: 4.5,
    reviewCount: 9,
    featured: false,
    trending: true,
    isNew: true,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2024-03-02T00:00:00Z',
    updatedAt: '2024-03-02T00:00:00Z'
  },
  {
    id: 'mock_4',
    title: 'Analytics Dashboard Pro',
    description: 'Advanced analytics dashboard with role-based views and custom charts.',
    shortDescription: 'Advanced analytics dashboard',
    sellerId: 'seller_7',
    sellerName: 'Maria Gomez',
    sellerAvatar: '/images/avatars/maria.jpg',
    techStack: ['React', 'Next.js', 'Tailwind CSS', 'D3.js'],
    framework: 'Next.js 14',
    database: 'PostgreSQL',
    deployment: ['Vercel', 'AWS'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/analytics-1.jpg'],
    price: 129.00,
    licenseType: 'extended',
    category: 'dashboard',
    tags: ['analytics', 'charts', 'saas'],
    downloads: 410,
    views: 3000,
    rating: 4.9,
    reviewCount: 52,
    featured: true,
    trending: true,
    isNew: false,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2023-12-15T00:00:00Z',
    updatedAt: '2024-02-01T00:00:00Z'
  },
  {
    id: 'mock_5',
    title: 'Landing Page Pack',
    description: 'Collection of 5 high-converting landing pages for different niches.',
    shortDescription: 'Pack of 5 landing pages',
    sellerId: 'seller_8',
    sellerName: 'Noah Lee',
    sellerAvatar: '/images/avatars/noah.jpg',
    techStack: ['Vue.js', 'Tailwind CSS'],
    framework: 'Nuxt 3',
    database: 'None',
    deployment: ['Vercel', 'Netlify'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/landing-pack-1.jpg'],
    price: 49.00,
    licenseType: 'commercial',
    category: 'landing-pages',
    tags: ['landing', 'vue', 'conversion'],
    downloads: 220,
    views: 1900,
    rating: 4.3,
    reviewCount: 18,
    featured: false,
    trending: false,
    isNew: false,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2023-10-10T00:00:00Z',
    updatedAt: '2023-12-01T00:00:00Z'
  },
  {
    id: 'mock_6',
    title: 'Blog Starter Kit',
    description: 'Feature-rich blog starter with MDX, comments, and RSS.',
    shortDescription: 'MDX blog starter',
    sellerId: 'seller_9',
    sellerName: 'Lara Knight',
    sellerAvatar: '/images/avatars/lara.jpg',
    techStack: ['Next.js', 'MDX', 'Tailwind CSS'],
    framework: 'Next.js 14',
    database: 'None',
    deployment: ['Vercel'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/blog-1.jpg'],
    price: 24.00,
    licenseType: 'personal',
    category: 'Web Templates',
    tags: ['blog', 'mdx'],
    downloads: 140,
    views: 1200,
    rating: 4.2,
    reviewCount: 10,
    featured: false,
    trending: false,
    isNew: true,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2024-03-03T00:00:00Z',
    updatedAt: '2024-03-03T00:00:00Z'
  },
  {
    id: 'mock_7',
    title: 'Tailwind Component Library',
    description: 'Reusable UI components for dashboards and apps.',
    shortDescription: 'Tailwind UI components',
    sellerId: 'seller_10',
    sellerName: 'Olivia Park',
    sellerAvatar: '/images/avatars/olivia.jpg',
    techStack: ['React', 'Tailwind CSS'],
    framework: 'Vite',
    database: 'None',
    deployment: ['Static Hosting'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/components-1.jpg'],
    price: 35.00,
    licenseType: 'commercial',
    category: 'UI/UX Kits',
    tags: ['components', 'ui'],
    downloads: 275,
    views: 2300,
    rating: 4.6,
    reviewCount: 21,
    featured: false,
    trending: true,
    isNew: false,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2023-09-01T00:00:00Z',
    updatedAt: '2023-11-15T00:00:00Z'
  },
  {
    id: 'mock_8',
    title: 'Node.js API Boilerplate',
    description: 'Secure and scalable Node.js REST API boilerplate with auth.',
    shortDescription: 'REST API boilerplate',
    sellerId: 'seller_11',
    sellerName: 'Ben Carter',
    sellerAvatar: '/images/avatars/ben.jpg',
    techStack: ['Node.js', 'Express', 'TypeScript'],
    framework: 'Node.js',
    database: 'PostgreSQL',
    deployment: ['AWS', 'Render'],
    browserCompat: ['Chrome'],
    mobileResponsive: false,
    screenshots: ['/images/projects/api-1.jpg'],
    price: 79.00,
    licenseType: 'commercial',
    category: 'backend-apis',
    tags: ['api', 'node', 'express'],
    downloads: 180,
    views: 1500,
    rating: 4.5,
    reviewCount: 17,
    featured: false,
    trending: false,
    isNew: false,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2023-08-12T00:00:00Z',
    updatedAt: '2023-10-05T00:00:00Z'
  },
  {
    id: 'mock_9',
    title: 'Stripe Payments Starter',
    description: 'Drop-in payments with Stripe checkout and webhooks.',
    shortDescription: 'Stripe payments starter',
    sellerId: 'seller_12',
    sellerName: 'Hannah Kim',
    sellerAvatar: '/images/avatars/hannah.jpg',
    techStack: ['Next.js', 'Stripe'],
    framework: 'Next.js 14',
    database: 'None',
    deployment: ['Vercel'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/stripe-1.jpg'],
    price: 45.00,
    licenseType: 'commercial',
    category: 'backend-apis',
    tags: ['stripe', 'payments'],
    downloads: 160,
    views: 1300,
    rating: 4.4,
    reviewCount: 15,
    featured: false,
    trending: true,
    isNew: false,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2023-11-01T00:00:00Z',
    updatedAt: '2023-12-20T00:00:00Z'
  },
  {
    id: 'mock_10',
    title: 'Chat App Template',
    description: 'Real-time chat app with Socket.io and authentication.',
    shortDescription: 'Real-time chat app',
    sellerId: 'seller_13',
    sellerName: 'Ethan Brooks',
    sellerAvatar: '/images/avatars/ethan.jpg',
    techStack: ['Next.js', 'Socket.io', 'Tailwind CSS'],
    framework: 'Next.js 14',
    database: 'MongoDB',
    deployment: ['Vercel', 'Railway'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/chat-1.jpg'],
    price: 99.00,
    licenseType: 'commercial',
    category: 'Web Templates',
    tags: ['chat', 'realtime'],
    downloads: 110,
    views: 1000,
    rating: 4.3,
    reviewCount: 11,
    featured: false,
    trending: false,
    isNew: true,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2024-03-04T00:00:00Z',
    updatedAt: '2024-03-04T00:00:00Z'
  },
  {
    id: 'mock_11',
    title: 'Marketing Site Template',
    description: 'Elegant marketing website template with sections and forms.',
    shortDescription: 'Marketing site template',
    sellerId: 'seller_14',
    sellerName: 'Sophie Turner',
    sellerAvatar: '/images/avatars/sophie.jpg',
    techStack: ['Next.js', 'Tailwind CSS'],
    framework: 'Next.js 14',
    database: 'None',
    deployment: ['Vercel', 'Netlify'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/marketing-1.jpg'],
    price: 29.00,
    licenseType: 'personal',
    category: 'landing-pages',
    tags: ['marketing', 'landing'],
    downloads: 95,
    views: 900,
    rating: 4.1,
    reviewCount: 8,
    featured: false,
    trending: false,
    isNew: true,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2024-03-05T00:00:00Z',
    updatedAt: '2024-03-05T00:00:00Z'
  },
  {
    id: 'mock_12',
    title: 'CMS Blog Admin',
    description: 'Admin panel for managing blog posts, categories, and authors.',
    shortDescription: 'CMS admin panel',
    sellerId: 'seller_15',
    sellerName: 'Victor Nguyen',
    sellerAvatar: '/images/avatars/victor.jpg',
    techStack: ['React', 'TypeScript', 'Tailwind CSS'],
    framework: 'Vite',
    database: 'Supabase',
    deployment: ['Vercel'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/cms-1.jpg'],
    price: 69.00,
    licenseType: 'commercial',
    category: 'dashboard',
    tags: ['cms', 'admin'],
    downloads: 130,
    views: 1100,
    rating: 4.2,
    reviewCount: 13,
    featured: false,
    trending: true,
    isNew: false,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2023-09-20T00:00:00Z',
    updatedAt: '2023-11-02T00:00:00Z'
  },
  {
    id: 'mock_13',
    title: 'Project Management UI',
    description: 'Kanban boards, tasks, and timelines UI template.',
    shortDescription: 'Project management UI',
    sellerId: 'seller_16',
    sellerName: 'Mina Patel',
    sellerAvatar: '/images/avatars/mina.jpg',
    techStack: ['React', 'Tailwind CSS', 'Framer Motion'],
    framework: 'Vite',
    database: 'None',
    deployment: ['Netlify'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/project-mgmt-1.jpg'],
    price: 75.00,
    licenseType: 'commercial',
    category: 'UI/UX Kits',
    tags: ['kanban', 'tasks'],
    downloads: 160,
    views: 1400,
    rating: 4.4,
    reviewCount: 14,
    featured: false,
    trending: true,
    isNew: false,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2023-10-01T00:00:00Z',
    updatedAt: '2023-12-01T00:00:00Z'
  },
  {
    id: 'mock_14',
    title: 'Auth Starter (NextAuth)',
    description: 'Prebuilt auth flows, email/password and OAuth with NextAuth.',
    shortDescription: 'NextAuth auth starter',
    sellerId: 'seller_17',
    sellerName: 'Tom Walker',
    sellerAvatar: '/images/avatars/tom.jpg',
    techStack: ['Next.js', 'NextAuth', 'Tailwind CSS'],
    framework: 'Next.js 14',
    database: 'PostgreSQL',
    deployment: ['Vercel'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/auth-1.jpg'],
    price: 55.00,
    licenseType: 'commercial',
    category: 'Web Templates',
    tags: ['auth', 'oauth'],
    downloads: 200,
    views: 1700,
    rating: 4.5,
    reviewCount: 19,
    featured: false,
    trending: false,
    isNew: false,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2023-07-15T00:00:00Z',
    updatedAt: '2023-09-01T00:00:00Z'
  },
  {
    id: 'mock_15',
    title: 'Analytics Widgets Pack',
    description: 'Collection of analytics widgets (charts, tables, metrics).',
    shortDescription: 'Analytics widgets',
    sellerId: 'seller_18',
    sellerName: 'Yuki Tanaka',
    sellerAvatar: '/images/avatars/yuki.jpg',
    techStack: ['React', 'Tailwind CSS', 'Chart.js'],
    framework: 'Vite',
    database: 'None',
    deployment: ['Static Hosting'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/widgets-1.jpg'],
    price: 39.00,
    licenseType: 'commercial',
    category: 'UI/UX Kits',
    tags: ['analytics', 'widgets'],
    downloads: 115,
    views: 980,
    rating: 4.2,
    reviewCount: 9,
    featured: false,
    trending: false,
    isNew: true,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2024-03-06T00:00:00Z',
    updatedAt: '2024-03-06T00:00:00Z'
  },
  {
    id: 'mock_16',
    title: 'Docs Site Template',
    description: 'Documentation site with search, sidebar nav, and dark mode.',
    shortDescription: 'Documentation site',
    sellerId: 'seller_19',
    sellerName: 'Ibrahim Ali',
    sellerAvatar: '/images/avatars/ibrahim.jpg',
    techStack: ['Next.js', 'MDX', 'Tailwind CSS'],
    framework: 'Next.js 14',
    database: 'None',
    deployment: ['Vercel'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/docs-1.jpg'],
    price: 42.00,
    licenseType: 'commercial',
    category: 'Web Templates',
    tags: ['docs', 'mdx'],
    downloads: 102,
    views: 870,
    rating: 4.1,
    reviewCount: 7,
    featured: false,
    trending: false,
    isNew: true,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2024-03-07T00:00:00Z',
    updatedAt: '2024-03-07T00:00:00Z'
  },
  {
    id: 'mock_17',
    title: 'Email Templates Pack',
    description: 'Responsive email templates for transactional and marketing emails.',
    shortDescription: 'Email templates pack',
    sellerId: 'seller_20',
    sellerName: 'Grace Lin',
    sellerAvatar: '/images/avatars/grace.jpg',
    techStack: ['HTML', 'MJML'],
    framework: 'MJML',
    database: 'None',
    deployment: ['Any'],
    browserCompat: ['All'],
    mobileResponsive: true,
    screenshots: ['/images/projects/email-1.jpg'],
    price: 27.00,
    licenseType: 'commercial',
    category: 'UI/UX Kits',
    tags: ['email', 'templates'],
    downloads: 210,
    views: 1600,
    rating: 4.3,
    reviewCount: 16,
    featured: false,
    trending: false,
    isNew: false,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2023-06-10T00:00:00Z',
    updatedAt: '2023-08-01T00:00:00Z'
  },
  {
    id: 'mock_18',
    title: 'Headless Commerce Starter',
    description: 'Headless commerce example with products, cart, and checkout.',
    shortDescription: 'Headless commerce',
    sellerId: 'seller_21',
    sellerName: 'Ravi Kumar',
    sellerAvatar: '/images/avatars/ravi.jpg',
    techStack: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    framework: 'Next.js 14',
    database: 'Supabase',
    deployment: ['Vercel'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/commerce-1.jpg'],
    price: 149.00,
    licenseType: 'extended',
    category: 'ecommerce',
    tags: ['commerce', 'headless'],
    downloads: 75,
    views: 900,
    rating: 4.4,
    reviewCount: 10,
    featured: true,
    trending: true,
    isNew: false,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2023-12-20T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z'
  },
  {
    id: 'mock_19',
    title: 'Portfolio Blocks',
    description: 'Composable portfolio blocks for galleries and case studies.',
    shortDescription: 'Composable portfolio blocks',
    sellerId: 'seller_22',
    sellerName: 'Natalie Brooks',
    sellerAvatar: '/images/avatars/natalie.jpg',
    techStack: ['React', 'Tailwind CSS'],
    framework: 'Vite',
    database: 'None',
    deployment: ['Netlify'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/blocks-1.jpg'],
    price: 33.00,
    licenseType: 'commercial',
    category: 'portfolio',
    tags: ['portfolio', 'blocks'],
    downloads: 88,
    views: 760,
    rating: 4.0,
    reviewCount: 6,
    featured: false,
    trending: false,
    isNew: true,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2024-03-08T00:00:00Z',
    updatedAt: '2024-03-08T00:00:00Z'
  },
  {
    id: 'mock_20',
    title: 'Startup Landing Bundle',
    description: 'Bundle of 3 startup landing pages with pricing and FAQ.',
    shortDescription: 'Startup landing bundle',
    sellerId: 'seller_23',
    sellerName: 'Zara Collins',
    sellerAvatar: '/images/avatars/zara.jpg',
    techStack: ['Next.js', 'Tailwind CSS'],
    framework: 'Next.js 14',
    database: 'None',
    deployment: ['Vercel'],
    browserCompat: ['Chrome', 'Firefox', 'Safari', 'Edge'],
    mobileResponsive: true,
    screenshots: ['/images/projects/startup-1.jpg'],
    price: 58.00,
    licenseType: 'commercial',
    category: 'landing-pages',
    tags: ['startup', 'landing'],
    downloads: 125,
    views: 980,
    rating: 4.2,
    reviewCount: 12,
    featured: false,
    trending: true,
    isNew: false,
    isRequestOnly: false,
    state: 'available_for_request',
    requiresApproval: false,
    autoApprove: false,
    maxRequestsPerBuyer: 1,
    totalRequests: 0,
    pendingRequests: 0,
    approvedRequests: 0,
    rejectedRequests: 0,
    completedRequests: 0,
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-02-15T00:00:00Z'
  }
];

export const getFeaturedProjects = () => projects.filter(p => p.featured);
export const getTrendingProjects = () => projects.filter(p => p.trending);
export const getNewProjects = () => projects.filter(p => p.isNew);
export const getProjectsByCategory = (category: string) => projects.filter(p => p.category === category);
