'use client';

// Mock organization data
export const ORGANIZATION_PROFILE = {
  id: 'org-1',
  name: 'TechCorp Solutions',
  logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=techcorp',
  industry: 'Technology',
  size: 'Large (1000+ employees)',
  plan: 'Enterprise',
  adminName: 'Jennifer Martinez',
  adminEmail: 'jennifer.martinez@techcorp.com',
  joinedDate: '2023-06-15',
  approvalStatus: 'approved', // pending | approved | rejected | suspended
  approvedDate: '2023-06-20',
  approvedBy: 'Platform Admin',
  tier: 'premium', // basic | premium | enterprise
  permissions: {
    createCourses: true,
    inviteEmployees: true,
    accessMarketplace: true,
    exportReports: true,
    customBranding: true,
    apiAccess: true,
  },
  settings: {
    allowSelfEnrollment: true,
    requireManagerApproval: false,
    enableCertificates: true,
    trackingEnabled: true,
  },
  verification: {
    businessRegistration: true,
    domainVerified: true,
    paymentMethodVerified: true,
    termsAccepted: true,
    minimumEmployees: true,
  },
};

// Mock employees
export const EMPLOYEES = [
  {
    id: 'emp-1',
    name: 'Alex Johnson',
    email: 'alex.johnson@techcorp.com',
    avatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=alex',
    department: 'Engineering',
    role: 'Senior Developer',
    manager: 'Sarah Wilson',
    hireDate: '2022-03-15',
    status: 'active', // active | inactive | pending
    learningGoals: ['React Mastery', 'System Design', 'Leadership Skills'],
  },
  {
    id: 'emp-2',
    name: 'Maria Rodriguez',
    email: 'maria.rodriguez@techcorp.com',
    avatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=maria',
    department: 'Engineering',
    role: 'Frontend Developer',
    manager: 'Sarah Wilson',
    hireDate: '2023-01-20',
    status: 'active',
    learningGoals: ['Advanced JavaScript', 'UI/UX Design', 'Testing'],
  },
  {
    id: 'emp-3',
    name: 'David Kim',
    email: 'david.kim@techcorp.com',
    avatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=david',
    department: 'Engineering',
    role: 'Backend Developer',
    manager: 'Sarah Wilson',
    hireDate: '2021-11-08',
    status: 'active',
    learningGoals: ['Node.js Mastery', 'Database Design', 'DevOps'],
  },
  {
    id: 'emp-4',
    name: 'Sarah Wilson',
    email: 'sarah.wilson@techcorp.com',
    avatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=sarah',
    department: 'Engineering',
    role: 'Engineering Manager',
    manager: 'Jennifer Martinez',
    hireDate: '2020-05-12',
    status: 'active',
    learningGoals: ['Leadership', 'Team Management', 'Strategic Planning'],
  },
  {
    id: 'emp-5',
    name: 'Michael Chen',
    email: 'michael.chen@techcorp.com',
    avatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=michael',
    department: 'Design',
    role: 'UX Designer',
    manager: 'Lisa Park',
    hireDate: '2022-09-03',
    status: 'active',
    learningGoals: ['Design Systems', 'User Research', 'Prototyping'],
  },
  {
    id: 'emp-6',
    name: 'Emily Davis',
    email: 'emily.davis@techcorp.com',
    avatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=emily',
    department: 'Design',
    role: 'Product Designer',
    manager: 'Lisa Park',
    hireDate: '2023-04-18',
    status: 'active',
    learningGoals: ['Figma Advanced', 'Design Thinking', 'Accessibility'],
  },
  {
    id: 'emp-7',
    name: 'James Thompson',
    email: 'james.thompson@techcorp.com',
    avatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=james',
    department: 'Data',
    role: 'Data Scientist',
    manager: 'Robert Lee',
    hireDate: '2021-07-22',
    status: 'active',
    learningGoals: ['Machine Learning', 'Python Advanced', 'Statistics'],
  },
  {
    id: 'emp-8',
    name: 'Lisa Park',
    email: 'lisa.park@techcorp.com',
    avatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=lisa',
    department: 'Design',
    role: 'Design Director',
    manager: 'Jennifer Martinez',
    hireDate: '2019-12-10',
    status: 'active',
    learningGoals: ['Design Leadership', 'Business Strategy', 'Team Building'],
  },
];

// Mock cohorts and assignments
export const COHORTS = [
  {
    id: 'cohort-1',
    name: 'Q1 2024 Frontend Bootcamp',
    description: 'Intensive React and JavaScript training for frontend developers',
    courseId: 'course-1',
    courseTitle: 'Complete React Development Bootcamp',
    startDate: '2024-01-15',
    endDate: '2024-04-15',
    status: 'active', // active | completed | upcoming
    instructor: 'Sarah Chen',
    maxParticipants: 20,
    participants: [
      {
        employeeId: 'emp-1',
        enrolledAt: '2024-01-10',
        progress: 85,
        lastActivity: '2024-03-10',
        status: 'on-track', // on-track | at-risk | completed | dropped
        completedLessons: 13,
        totalLessons: 15,
        averageScore: 88,
        timeSpent: 2340, // minutes
      },
      {
        employeeId: 'emp-2',
        enrolledAt: '2024-01-10',
        progress: 92,
        lastActivity: '2024-03-12',
        status: 'on-track',
        completedLessons: 14,
        totalLessons: 15,
        averageScore: 94,
        timeSpent: 2680,
      },
      {
        employeeId: 'emp-3',
        enrolledAt: '2024-01-10',
        progress: 45,
        lastActivity: '2024-02-28',
        status: 'at-risk',
        completedLessons: 7,
        totalLessons: 15,
        averageScore: 72,
        timeSpent: 1120,
      },
      {
        employeeId: 'emp-5',
        enrolledAt: '2024-01-12',
        progress: 78,
        lastActivity: '2024-03-08',
        status: 'on-track',
        completedLessons: 12,
        totalLessons: 15,
        averageScore: 86,
        timeSpent: 2100,
      },
    ],
  },
  {
    id: 'cohort-2',
    name: 'Advanced JavaScript Mastery',
    description: 'Deep dive into advanced JavaScript concepts for senior developers',
    courseId: 'course-7',
    courseTitle: 'Advanced JavaScript Patterns',
    startDate: '2024-02-01',
    endDate: '2024-03-30',
    status: 'completed',
    instructor: 'Sarah Chen',
    maxParticipants: 15,
    participants: [
      {
        employeeId: 'emp-1',
        enrolledAt: '2024-01-25',
        progress: 100,
        lastActivity: '2024-03-28',
        status: 'completed',
        completedLessons: 12,
        totalLessons: 12,
        averageScore: 91,
        timeSpent: 1890,
      },
      {
        employeeId: 'emp-4',
        enrolledAt: '2024-01-25',
        progress: 100,
        lastActivity: '2024-03-30',
        status: 'completed',
        completedLessons: 12,
        totalLessons: 12,
        averageScore: 95,
        timeSpent: 2150,
      },
      {
        employeeId: 'emp-7',
        enrolledAt: '2024-01-28',
        progress: 83,
        lastActivity: '2024-03-25',
        status: 'completed',
        completedLessons: 10,
        totalLessons: 12,
        averageScore: 87,
        timeSpent: 1650,
      },
    ],
  },
  {
    id: 'cohort-3',
    name: 'UX Design Fundamentals',
    description: 'Essential UX design skills for product teams',
    courseId: 'course-3',
    courseTitle: 'UI/UX Design Fundamentals',
    startDate: '2024-03-15',
    endDate: '2024-05-15',
    status: 'upcoming',
    instructor: 'Elena Rodriguez',
    maxParticipants: 12,
    participants: [
      {
        employeeId: 'emp-5',
        enrolledAt: '2024-03-10',
        progress: 0,
        lastActivity: null,
        status: 'enrolled',
        completedLessons: 0,
        totalLessons: 10,
        averageScore: 0,
        timeSpent: 0,
      },
      {
        employeeId: 'emp-6',
        enrolledAt: '2024-03-10',
        progress: 0,
        lastActivity: null,
        status: 'enrolled',
        completedLessons: 0,
        totalLessons: 10,
        averageScore: 0,
        timeSpent: 0,
      },
      {
        employeeId: 'emp-8',
        enrolledAt: '2024-03-12',
        progress: 0,
        lastActivity: null,
        status: 'enrolled',
        completedLessons: 0,
        totalLessons: 10,
        averageScore: 0,
        timeSpent: 0,
      },
    ],
  },
];

// Mock learning tracks (collections of courses)
export const LEARNING_TRACKS = [
  {
    id: 'track-1',
    name: 'Full-Stack Developer Path',
    description: 'Complete journey from frontend to backend development',
    courses: ['course-1', 'course-2', 'course-6'],
    estimatedDuration: '6 months',
    difficulty: 'Intermediate to Advanced',
    prerequisites: 'Basic programming knowledge',
    learningOutcomes: [
      'Build complete web applications',
      'Master modern JavaScript frameworks',
      'Understand backend architecture',
      'Deploy applications to production',
    ],
    enrolledEmployees: 15,
    completionRate: 73,
  },
  {
    id: 'track-2',
    name: 'Design Excellence Program',
    description: 'Comprehensive design skills for product teams',
    courses: ['course-3'],
    estimatedDuration: '3 months',
    difficulty: 'Beginner to Intermediate',
    prerequisites: 'None',
    learningOutcomes: [
      'Create user-centered designs',
      'Master design tools and processes',
      'Conduct user research',
      'Build design systems',
    ],
    enrolledEmployees: 8,
    completionRate: 85,
  },
  {
    id: 'track-3',
    name: 'Data Science Fundamentals',
    description: 'Essential data science skills for analysts and engineers',
    courses: ['course-4'],
    estimatedDuration: '4 months',
    difficulty: 'Intermediate',
    prerequisites: 'Basic Python knowledge',
    learningOutcomes: [
      'Analyze complex datasets',
      'Build machine learning models',
      'Create data visualizations',
      'Make data-driven decisions',
    ],
    enrolledEmployees: 6,
    completionRate: 67,
  },
];

// Mock analytics data
export const ORG_ANALYTICS = {
  overview: {
    totalEmployees: EMPLOYEES.length,
    activeEnrollments: 24,
    completedCourses: 18,
    averageProgress: 76,
    totalLearningHours: 1247,
    certificatesEarned: 12,
  },
  departmentBreakdown: {
    Engineering: { employees: 4, enrollments: 12, completion: 78 },
    Design: { employees: 3, enrollments: 8, completion: 85 },
    Data: { employees: 1, enrollments: 4, completion: 67 },
  },
  monthlyProgress: [
    { month: 'Jan', enrollments: 8, completions: 2 },
    { month: 'Feb', enrollments: 12, completions: 5 },
    { month: 'Mar', enrollments: 15, completions: 8 },
    { month: 'Apr', enrollments: 18, completions: 12 },
    { month: 'May', enrollments: 24, completions: 18 },
  ],
  skillsGaps: [
    { skill: 'React', demand: 85, supply: 60, gap: 25 },
    { skill: 'Node.js', demand: 70, supply: 45, gap: 25 },
    { skill: 'Design Systems', demand: 60, supply: 40, gap: 20 },
    { skill: 'Machine Learning', demand: 50, supply: 25, gap: 25 },
  ],
};

// Lesson completion heatmap data
export const LESSON_HEATMAP_DATA = {
  'cohort-1': {
    lessons: [
      'Introduction to React',
      'JSX and Components', 
      'Props and State',
      'Event Handling',
      'React Basics Quiz',
      'React Hooks Introduction',
      'useState and useEffect',
      'Custom Hooks',
      'Context API',
      'Advanced React Project',
      'React Router',
      'State Management with Redux',
      'Testing React Applications',
      'Performance Optimization',
      'Final Capstone Project',
    ],
    completionMatrix: [
      // Each row is an employee, each column is a lesson (1 = completed, 0 = not completed)
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0], // emp-1
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0], // emp-2
      [1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], // emp-3
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0], // emp-5
    ],
  },
};
